sudo: required

services:
  - docker

before_install:
  - docker build -t abhishekkprasad/docker-react -f Dockerfile.dev .

script:
  - docker run abhishekkprasad/docker-react npm run test -- --coverage
